db:
  image: postgres:9.0.22
  container_name: credo_db
  environment:
    POSTGRES_DB: credo_server_stg
web:
  build: .
  command: monit -I
  environment:
    PORT: 4000
  container_name: credo_web
  ports:
   - "4000:4000"
  links:
    - db
