db:
  image: postgres:9.0.22
  container_name: credo_db
web:
  build: .
  command: mix phoenix.server
  environment:
    MIX_ENV: dev
    PORT: 4000
  container_name: credo_staging_web
  ports:
   - "4000:4000"
  links:
    - db
